### PR TITLE
Create a pip installable python package 'drone_sim' with whl distribution

### LINKED ISSUE #5: Proper Installation procedure using pip
Add a proper installation procedure for using it through pip install

### PR DESCRIPTION
**Pull request by acestark12**
## Changes made
- Added the setup.py file with the available credential using setuptools and made a namespace package
- Removed the __ init __.py file from drone_sim folder as it is a namespace package, hence not required
- Added the .whl distribution in the dist folder

## How to install with pip
- Clone the repository in desktop
- Open command line in the dist folder of drone_sim (ex. - ...\\drone_sim\\dist)
-  then run the following command
  `python -m pip install <.whl filename>`
   filename= "Drone_Simulator-0.1.0-py3-none-any.whl"
------------------------------------------------**_or_**------------------------------------------------------
- Open command line and run the following command
 `python -m pip install git+<repository link>`

### CODE REVIEW

**Comment by acestark12** [comment]
@SuhrudhSarathy could you please review this?

**Comment by SuhrudhSarathy** [comment]
Hey!
The setup.py looks good to me. I don't think its necessary to include the build files into the main branch. Could you make a separate branch `build` which has the build files, egg info etc. and on the main branch just keep the `setup.py`, `requirements.txt` without the build and whl file? I think that should be good. Send a PR after you have modified the README.txt in both the branches.

**Comment by acestark12** [comment]
Hey @SuhrudhSarathy 
I have made the changes as you said. I had just one suggestion that in the requirements, Could you keep
`matplotlib>=3.4.3`
`numpy>=1.21.2`
 if the code is compatible for higher versions? that way it won't force the user's updated library to roll-back while installing the drone_sim package.

**Comment by SuhrudhSarathy** [comment]
Great! Looks good to me!

**Pull request merged**
